### ISSUE TITLE
Summary of *Automate the Boring Stuff with Python* | Scott's Blog

### ISSUE THREAD

**Issue by yeung66** [yeung66/yeung66.github.io#29]
http://scottyeung.club/2019/Summary-of-Automate-the-Boring-Stuff-with-Python/#more 

 本书是为如何用Python进行自动化处理工作以及可以用在哪些方面，面向的人群为想要提高生产力，减少重复劳动的非程序员。 作为一个未来的程序员，我为什么推荐这本面向非程序员的书呢？在我看来，code是一个工具，既然是一种工具，就应该用于帮助解决问题和满足需求。但实际上，在我们许多的coding相关的学习中，我们并没有考虑why，而是简单粗暴地去学习what，这样学习效率不高，而且最关键的是会有一种不

**Comment by eternalaudrey** [comment]
您好，想请问您这个网站是用什么框架搭建的？谢谢！

**Comment by yeung66** [comment]
> @eternalaudrey
> 您好，想请问您这个网站是用什么框架搭建的？谢谢！

hexo
